export enum NOTIFICATION_PURPOSE {
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
    WELCOME_EMAIL = "WELCOME_EMAIL",
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    REFUND_INITIATED = "REFUND_INITIATED",
    ORDER_SHIPPED = "ORDER_SHIPPED"
}